out_base_path: resources/outputs/${data.file_name}/${name}

raw_data: resources/raw_data/${data.name}/${data.file_name}.csv
processed_data: ${path.out_base_path}/processed_data/${run_id}/${data.name}
models: ${path.out_base_path}/models/${run_id}
pickles: ${path.out_base_path}/pickles/${run_id}
tb_logs: ${path.out_base_path}/tb/${seed}
json_logs: ${path.out_base_path}/json/${seed}/${run_id}
checkpoints: ${path.out_base_path}/checkpoints/${run_id}
