out_base_path: resources/outputs/${data.name}/${name}

raw_data: resources/raw_data/dataset_v2
processed_data: ${path.out_base_path}/processed_data
models: ${path.out_base_path}/models
pickles: ${path.out_base_path}/pickles
tb_logs: ${path.out_base_path}/tb/${seed}
json_logs: ${path.out_base_path}/json/${seed}
checkpoints: ${path.out_base_path}/checkpoints
