out_base_path: resources/experiments/${name}/${data.file_name}_${seed}
# inputs
raw_data: resources/raw_data/${data.dir}/${data.file_name}.csv

# per-run outputs
processed_data: ${path.out_base_path}/${run_id}/processed_data
models: ${path.out_base_path}/${run_id}/models
json_logs: ${path.out_base_path}/${run_id}/logs
configs: ${path.out_base_path}/${run_id}/configs

# shared across runs (for TensorBoard comparison)
tb_logs: ${path.out_base_path}/tb
