name: tabular_autoencoder

params:
  num_numerical_features: ${data.num_numerical}
  num_categorical_features: ${data.num_categorical}
  max_emb_dim: 24
  noise_factor: 0.0

  # Architecture
  latent_dim: 32
  hidden_dims: [128, 64]
  dropout: 0.1
