name: tabular_classifier

params:
  num_numerical_features: ${data.num_numerical}
  num_categorical_features: ${data.num_categorical}
  max_emb_dim: 24

  # Architecture
  hidden_dims: [128, 64, 32]
  dropout: 0.1
  num_classes: 11 # 10 attack + 1 benign
