name: cluster_batch_sampler

params:
  batch_size: 512
  clusters_per_batch: 8
  samples_per_cluster: 63
  include_ambiguous: 8
  ambiguous_tag: -1
  drop_last: True
  min_cluster_size: 2
  seed: ${seed}
