defaults:
  - data: cic_2018_v2
  - loops: default
  - model: tabular_classifier
  - loss: classification
  - optimizer: adamw
  - scheduler: one_cycle
  - sampler: null
  - _self_
  - experiment: supervised
  - path: default

seed: 42
name: supervised_bg
device: cpu
run_id: 0
stage: all



hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
